### ISSUE TITLE
Browser Autocomplete

### ISSUE THREAD

**Issue by mikeymike** [PCAPredict/magento2#19]
This potentially isn't the right place for this but on the assumption you guys also control the external JS that gets pulled in then it's one way to report this issue. 

With automcomplete in Chrome it seems to ignore the `autocomplete=off` value which based on the JS from [this source](https://services.postcodeanywhere.co.uk/js/platformcaptureplus-2.20.min.js) (when you unminify it) it seems like you're aware of this issue because there's some browser checks and version checks  that decide whether to change the `automplete` attribute value to `off` or `pca-override`

Using `pca-override` is fine to disable autocomplete and it seems to be what is recommended. However it looks like the version checks are only targeting version 63 while the behaviour is still the same in the latest Chrome version `67` and Canary `69`. Essentially it's still using `off` in the latest Chrome which doesn't disable autcomplete. 

My hope is this issue will prompt a resolution upstream 🤞

**Comment by henrikvalve** [comment]
Hi Mike,

Thanks for this, I'll feedback to the person who owns these script files. For the time being, if you do not want us to add the autocomplete attribute to your fields, please use this code snippet in the 'custom code' section available in our plugin settings: 

`pca.on("options", function(type, id, options) { 
    options.suppressAutocomplete = false; 
}); `

You will then be able to push your own autocomplete attribute instead. 

Best,

Henrik

**Comment by mikeymike** [comment]
thanks @henrikvalve! at least we have a workaround 👍 ... feel free to close this

**Comment by henrikvalve** [comment]
No problem, thanks for reporting!
