### ISSUE TITLE
Feature Request: Admin Panel Lookups

### ISSUE THREAD

**Issue by richardjkeys** [PCAPredict/magento2#5]
Are there any plans to add address validation in the Magento 2 Admin Area?

**Comment by rikhowarth** [comment]
There are parts of the admin section that already work, such as the sales order edit screens (editing billing or shipping address) as well as adding/editing the customer addresses, although this one has issues if the customer has multiple addresses.

There are other areas such as creating an order for a customer, that aren't currently covered, and may be considered for a later release.

**Comment by richardjkeys** [comment]
Ah, that's the section I was looking at. Thanks for clarifying!
