### ISSUE TITLE
Packagist

### ISSUE THREAD

**Issue by adamj88** [PCAPredict/magento2#7]
Would you be open to publishing this to [packagist](https://packagist.org/) so we are able to skip this step? 

```
composer config repositories.pca-predict vcs https://github.com/PCAPredict/magento2.git
```

**Comment by ghost** [comment]
Hi Adam,

We are looking into that now. Will message you when everything is setup.

**Comment by ghost** [comment]
Hi @adamj88 

Sorry for the late reply, we went through a big change with how the app sets up the keys on an account and the general logic it uses in the Magento store. I had to pull that in from our internal development source.

Here's our project in packagist, with the latest version https://packagist.org/packages/pcapredict/tag

If you have any problems with installing the new version, don't hesitate to contact support and they will be able to guide you through it. There were some fundamental changes so fully uninstalling the old version might be best before installing the latest.

Regards

**Comment by adamj88** [comment]
No problem @mattgarde - thanks for getting this set up on packagist 👍
